apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi

