apiVersion: batch/v1
kind: Job
metadata:
  name: mount
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: mount-pv-storage
          persistentVolumeClaim:
            claimName: mount-pv-claim
        - name: plugin-dir
          hostPath:
            path: /test-mount-pv/test-volume
            type: DirectoryOrCreate
      containers:
          - name: test1
            image: fedora:32
            imagePullPolicy: IfNotPresent
            command:
            - mount
            args:
            - "--rbind"
            - "/src"
            - "/dst"
            securityContext:
              privileged: true 
            volumeMounts:
            - name: mount-pv-storage
              mountPath: /dst
              mountPropagation: "Bidirectional"
            - name: plugin-dir
              mountPath: /src
              mountPropagation: "Bidirectional"
