apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  volumes:
    - name: test-mount
      persistentVolumeClaim:
        claimName: mount-pv-claim 
  containers:
  - name: test1
    image: fedora
    args:
    - sleep
    - "1000000"
    volumeMounts:
    - mountPath: "/test"
      name: test-mount
